# Generated by Django 4.2 on 2023-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_real_info',
            field=models.BooleanField(default=False),
        ),
    ]
