# Generated by Django 3.2.18 on 2023-06-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=50, verbose_name='内容')),
                ('readCheck', models.BooleanField(default=False)),
                ('sendTime', models.DateTimeField(default=None, null=True, verbose_name='发送时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='chatinfo',
            index=models.Index(fields=['sender', 'receiver'], name='chat_chatin_sender__93550d_idx'),
        ),
    ]
