# Generated by Django 4.2 on 2023-06-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=200, verbose_name='对应作品的open_alex_id')),
                ('user_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
