# Generated by Django 4.2 on 2023-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.CharField(db_index=True, default='', max_length=200, primary_key=True, serialize=False, verbose_name='对应作品的open_alex_id')),
                ('work_name', models.CharField(db_index=True, default='', max_length=200, verbose_name='论文的名字')),
                ('author_id', models.CharField(db_index=True, default='', max_length=200, verbose_name='上传pdf的作者的open_alex_id')),
                ('url', models.CharField(max_length=200, null=True, verbose_name='论文的访问路由')),
                ('pdf', models.FileField(default='', upload_to='', verbose_name='文章pdf')),
                ('has_pdf', models.IntegerField(default=-1, verbose_name='是否有pdf')),
                ('content', models.TextField()),
                ('send_time', models.DateTimeField(verbose_name='上传时间')),
                ('author', models.CharField(default='', max_length=200, verbose_name='上传pdf的作者')),
                ('category', models.CharField(default='', max_length=200, verbose_name='论文分类')),
            ],
        ),
    ]
